#import "CameraViewController.h"
#import <AVFoundation/AVFoundation.h>
#import <CoreImage/CoreImage.h>
@interface CameraViewController () <AVCaptureVideoDataOutputSampleBufferDelegate>
@property AVCaptureSession *session; @property dispatch_queue_t queue; @property CIContext *context; @property UIImageView *imageView; @property UISlider *slider; @property UIImage *latestImage;
@end
@implementation CameraViewController
- (void)viewDidLoad { [super viewDidLoad]; self.view.backgroundColor=UIColor.blackColor; self.queue=dispatch_queue_create("camera.frames",DISPATCH_QUEUE_SERIAL); self.context=[CIContext contextWithOptions:nil]; [self setupUI]; [self startCamera]; }
- (void)setupUI { self.imageView=[[UIImageView alloc] initWithFrame:self.view.bounds]; self.imageView.contentMode=UIViewContentModeScaleAspectFill; [self.view addSubview:self.imageView]; self.slider=[[UISlider alloc] initWithFrame:CGRectMake(24,self.view.bounds.size.height-90,self.view.bounds.size.width-48,40)]; self.slider.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleTopMargin; self.slider.minimumValue=0; self.slider.maximumValue=.04; self.slider.value=.012; [self.view addSubview:self.slider]; UIButton *button=[UIButton buttonWithType:UIButtonTypeSystem]; button.frame=CGRectMake(self.view.bounds.size.width/2-35,self.view.bounds.size.height-155,70,55); button.autoresizingMask=UIViewAutoresizingFlexibleTopMargin|UIViewAutoresizingFlexibleLeftMargin|UIViewAutoresizingFlexibleRightMargin; [button setTitle:@"●" forState:UIControlStateNormal]; button.titleLabel.font=[UIFont systemFontOfSize:48]; [button addTarget:self action:@selector(savePhoto) forControlEvents:UIControlEventTouchUpInside]; [self.view addSubview:button]; }
- (void)startCamera { self.session=[AVCaptureSession new]; self.session.sessionPreset=AVCaptureSessionPreset1280x720; AVCaptureDevice *device=[AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo]; AVCaptureDeviceInput *input=[AVCaptureDeviceInput deviceInputWithDevice:device error:nil]; if([self.session canAddInput:input])[self.session addInput:input]; AVCaptureVideoDataOutput *output=[AVCaptureVideoDataOutput new]; output.videoSettings=@{(id)kCVPixelBufferPixelFormatTypeKey:@(kCVPixelFormatType_32BGRA)}; [output setSampleBufferDelegate:self queue:self.queue]; if([self.session canAddOutput:output])[self.session addOutput:output]; AVAuthorizationStatus status=[AVCaptureDevice authorizationStatusForMediaType:AVMediaTypeVideo]; if(status==AVAuthorizationStatusNotDetermined)[AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL ok){if(ok)dispatch_async(dispatch_get_main_queue(),^{[self.session startRunning];});}]; else if(status==AVAuthorizationStatusAuthorized)[self.session startRunning]; }
- (CIImage *)processedImage:(CIImage *)image { CGFloat o=self.slider.value*image.extent.size.width; NSDictionary *r=@{ @"inputRVector":[CIVector vectorWithX:1 Y:0 Z:0 W:0], @"inputGVector":[CIVector vectorWithX:0 Y:0 Z:0 W:0], @"inputBVector":[CIVector vectorWithX:0 Y:0 Z:0 W:0] }; NSDictionary *b=@{ @"inputRVector":[CIVector vectorWithX:0 Y:0 Z:0 W:0], @"inputGVector":[CIVector vectorWithX:0 Y:0 Z:0 W:0], @"inputBVector":[CIVector vectorWithX:0 Y:0 Z:1 W:0] }; CIImage *red=[[image imageByApplyingFilter:@"CIColorMatrix" withInputParameters:r] imageByApplyingTransform:CGAffineTransformMakeTranslation(-o,0)]; CIImage *blue=[[image imageByApplyingFilter:@"CIColorMatrix" withInputParameters:b] imageByApplyingTransform:CGAffineTransformMakeTranslation(o,0)]; return [blue imageByCompositingOverImage:red]; }
- (void)captureOutput:(AVCaptureOutput *)output didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection { CIImage *result=[self processedImage:[CIImage imageWithCVPixelBuffer:CMSampleBufferGetImageBuffer(sampleBuffer)]]; CGImageRef cg=[self.context createCGImage:result fromRect:result.extent]; UIImage *frame=[UIImage imageWithCGImage:cg scale:1 orientation:UIImageOrientationRight]; CGImageRelease(cg); dispatch_async(dispatch_get_main_queue(),^{self.latestImage=frame; self.imageView.image=frame;}); }
- (void)savePhoto { if(self.latestImage) UIImageWriteToSavedPhotosAlbum(self.latestImage,self,@selector(image:didFinishSavingWithError:contextInfo:),NULL); }
- (void)image:(UIImage *)image didFinishSavingWithError:(NSError *)error contextInfo:(void *)contextInfo { if(error) NSLog(@"Save error: %@",error); }
@end
